// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCHRka8J2zWaPh6MYMz7Q3iPwU7W6_0ac',
    appId: '1:875188619759:web:aa754f428066adc6cace1a',
    messagingSenderId: '875188619759',
    projectId: 'firstproject-67f96',
    authDomain: 'firstproject-67f96.firebaseapp.com',
    storageBucket: 'firstproject-67f96.appspot.com',
    measurementId: 'G-XG932TV89B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiwL81M7XKfr7YBHKhN__egrHNgdBEA4U',
    appId: '1:875188619759:android:ea4c2d4df2899905cace1a',
    messagingSenderId: '875188619759',
    projectId: 'firstproject-67f96',
    storageBucket: 'firstproject-67f96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD21jqBKjkhBu5ZSKBLp21PLvzU2PqE6WY',
    appId: '1:875188619759:ios:e7f335bc7699e9eecace1a',
    messagingSenderId: '875188619759',
    projectId: 'firstproject-67f96',
    storageBucket: 'firstproject-67f96.appspot.com',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD21jqBKjkhBu5ZSKBLp21PLvzU2PqE6WY',
    appId: '1:875188619759:ios:d988786c6b206004cace1a',
    messagingSenderId: '875188619759',
    projectId: 'firstproject-67f96',
    storageBucket: 'firstproject-67f96.appspot.com',
    iosBundleId: 'com.example.firstproject.RunnerTests',
  );
}
